import stylistic from "@stylistic/eslint-plugin";
import typescriptEslint from "@typescript-eslint/eslint-plugin";
import prettierConfig from "eslint-config-prettier";
import prettier from "eslint-plugin-prettier";
import sonarjs from "eslint-plugin-sonarjs";
import { defineConfig } from "eslint/config";

const sharedRules = {
    ...sonarjs.configs.recommended.rules,
    ...prettierConfig.rules,
    quotes: "off",
    "@stylistic/quotes": ["error", "double"],
    semi: "off",
    indent: "off",
    "comma-dangle": "off",
    "comma-spacing": "off",
    "dot-notation": "error",
    "keyword-spacing": "off",
    "no-dupe-class-members": "error",
    "no-invalid-this": "error",
    "no-loop-func": "error",
    "no-shadow": "error",
    "no-unused-expressions": "error",
    "no-useless-constructor": "error",
    "space-infix-ops": "off",
    "object-curly-spacing": "off",
    "require-await": "off",
    "space-before-function-paren": "off",
    "no-empty-function": ["warn"],
    "no-promise-executor-return": "error",
    "array-bracket-spacing": ["error", "never"],
    curly: ["error", "all"],
    eqeqeq: ["error", "always"],
    "guard-for-in": "error",
    "multiline-comment-style": ["error", "separate-lines"],
    "no-confusing-arrow": "error",
    "no-else-return": "error",
    "no-floating-decimal": "error",
    "no-inline-comments": "error",
    "no-lonely-if": "error",
    "no-mixed-operators": "error",
    "no-multi-assign": "error",
    "no-negated-condition": "error",
    "no-nested-ternary": "error",
    "no-param-reassign": "error",
    "prefer-const": "error",
    "prefer-template": "error",
    "spaced-comment": ["error", "always"],
    "arrow-parens": ["error", "always"],
    "arrow-spacing": "error",
    "block-spacing": "error",
    "computed-property-spacing": ["error", "never"],
    "dot-location": ["error", "property"],
    "eol-last": ["error", "always"],
    "func-call-spacing": ["error", "never"],
    "function-call-argument-newline": ["error", "consistent"],
    "implicit-arrow-linebreak": ["off", "beside"],
    "key-spacing": "error",
    "new-parens": "error",
    "no-multi-spaces": "error",
    "no-multiple-empty-lines": "error",
    "no-tabs": "error",
    "no-trailing-spaces": "error",
    "no-unused-vars": "warn",
    "no-whitespace-before-property": "error",
    "rest-spread-spacing": "error",
    "semi-spacing": "error",
    "semi-style": "error",
    "space-before-blocks": "error",
    "space-unary-ops": "error",
    "switch-colon-spacing": "error",
    "template-curly-spacing": "error",
    "prettier/prettier": "warn",
    "sonarjs/no-commented-code": "warn",
    "sonarjs/cognitive-complexity": "warn",
};

const typescriptRules = {
    ...typescriptEslint.configs.recommended.rules,
    ...typescriptEslint.configs["recommended-requiring-type-checking"].rules,
    "@typescript-eslint/no-unused-vars": "warn",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@stylistic/member-delimiter-style": "error",
    "@typescript-eslint/member-ordering": "warn",
    "@typescript-eslint/no-base-to-string": "error",
    "@typescript-eslint/no-confusing-non-null-assertion": "error",
    "@typescript-eslint/no-confusing-void-expression": "error",
    "@typescript-eslint/no-require-imports": "error",
    "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
    "@typescript-eslint/no-unnecessary-condition": "warn",
    "@typescript-eslint/no-unnecessary-type-arguments": "error",
    "@typescript-eslint/prefer-for-of": "error",
    "@typescript-eslint/prefer-includes": "error",
    "@typescript-eslint/prefer-nullish-coalescing": "warn",
    "@typescript-eslint/prefer-optional-chain": "error",
    "@typescript-eslint/prefer-readonly": "error",
    "@typescript-eslint/prefer-reduce-type-parameter": "error",
    "@typescript-eslint/prefer-regexp-exec": "error",
    "@typescript-eslint/prefer-return-this-type": "error",
    "@typescript-eslint/prefer-string-starts-ends-with": "error",
    "@typescript-eslint/strict-boolean-expressions": "off",
    "@typescript-eslint/default-param-last": "error",
    "@typescript-eslint/dot-notation": "error",
    "@typescript-eslint/no-dupe-class-members": "error",
    "@typescript-eslint/no-invalid-this": "error",
    "@typescript-eslint/no-loop-func": "error",
    "@typescript-eslint/no-shadow": "error",
    "@typescript-eslint/no-unused-expressions": "error",
    "@typescript-eslint/no-useless-constructor": "error",
    "@typescript-eslint/no-empty-function": ["warn"],
    "@typescript-eslint/require-await": "off",
};

export default defineConfig([
    {
        ignores: ["**/eslint.config.js", "dist"],
    },
    {
        plugins: {
            "@stylistic": stylistic,
            sonarjs: sonarjs,
            prettier: prettier,
        },
        files: ["**/*.js", "**/*.ts", "**/*.jsx", "**/*.tsx"],
        rules: sharedRules,
    },
    {
        files: ["**/*.ts", "**/*.tsx"],
        plugins: {
            "@typescript-eslint": typescriptEslint,
            "@stylistic": stylistic,
        },
        rules: {
            "no-unused-vars": "off",
            "default-param-last": "off",
            "dot-notation": "off",
            "no-dupe-class-members": "off",
            "no-invalid-this": "off",
            "no-loop-func": "off",
            "no-shadow": "off",
            "no-unused-expressions": "off",
            "no-useless-constructor": "off",
            "no-empty-function": "off",
            ...typescriptRules,
        },
    },
]);
