import stylistic from "@stylistic/eslint-plugin";
import typescriptEslint from "@typescript-eslint/eslint-plugin";
import prettierConfig from "eslint-config-prettier";
import prettier from "eslint-plugin-prettier";
import sonarjs from "eslint-plugin-sonarjs";
import { defineConfig } from "eslint/config";

export default defineConfig([
    {
        ignores: ["**/eslint.config.js", "dist"],
    },
    {
        plugins: {
            "@typescript-eslint": typescriptEslint,
            "@stylistic": stylistic,
            sonarjs: sonarjs,
            prettier: prettier,
        },
        files: ["**/*.js", "**/*.ts", "**/*.jsx", "**/*.tsx"],
        rules: {
            ...typescriptEslint.configs.recommended.rules,
            ...typescriptEslint.configs["recommended-requiring-type-checking"]
                .rules,
            ...sonarjs.configs.recommended.rules,
            ...prettierConfig.rules,
            "@typescript-eslint/no-unused-vars": "warn",
            "@typescript-eslint/explicit-function-return-type": "off",
            "@stylistic/member-delimiter-style": "error",
            "@typescript-eslint/member-ordering": "warn",
            "@typescript-eslint/no-base-to-string": "error",
            "@typescript-eslint/no-confusing-non-null-assertion": "error",
            "@typescript-eslint/no-confusing-void-expression": "error",
            "@typescript-eslint/no-require-imports": "error",
            "@typescript-eslint/no-unnecessary-boolean-literal-compare":
                "error",
            "@typescript-eslint/no-unnecessary-condition": "warn",
            "@typescript-eslint/no-unnecessary-type-arguments": "error",
            "@typescript-eslint/prefer-for-of": "error",
            "@typescript-eslint/prefer-includes": "error",
            "@typescript-eslint/prefer-nullish-coalescing": "warn",
            "@typescript-eslint/prefer-optional-chain": "error",
            "@typescript-eslint/prefer-readonly": "error",
            "@typescript-eslint/prefer-reduce-type-parameter": "error",
            "@typescript-eslint/prefer-regexp-exec": "error",
            "@typescript-eslint/prefer-return-this-type": "error",
            "@typescript-eslint/prefer-string-starts-ends-with": "error",
            // "@typescript-eslint/sort-type-union-intersection-members": "error",
            "@typescript-eslint/strict-boolean-expressions": "off",
            // "@typescript-eslint/type-annotation-spacing": "error",
            quotes: "off",
            "@stylistic/quotes": ["error", "double"],
            semi: "off",
            // "@typescript-eslint/semi": ["error", "always"],
            indent: "off",
            "comma-dangle": "off",
            // "@typescript-eslint/comma-dangle": [
            //     "error",
            //     {
            //         arrays: "always-multiline",
            //         objects: "always-multiline",
            //         imports: "always-multiline",
            //         exports: "always-multiline",
            //         functions: "always-multiline",
            //         enums: "always-multiline",
            //         generics: "always-multiline",
            //         tuples: "always-multiline",
            //     },
            // ],
            "comma-spacing": "off",
            // "@typescript-eslint/comma-spacing": "error",
            "@typescript-eslint/default-param-last": "error",
            "dot-notation": "off",
            "@typescript-eslint/dot-notation": "error",
            "keyword-spacing": "off",
            // "@typescript-eslint/keyword-spacing": "error",
            "no-dupe-class-members": "off",
            "@typescript-eslint/no-dupe-class-members": "error",
            "no-duplicate-imports": "off",
            // "@typescript-eslint/no-duplicate-imports": "error",
            "no-invalid-this": "off",
            "@typescript-eslint/no-invalid-this": "error",
            "no-loop-func": "off",
            "@typescript-eslint/no-loop-func": "error",
            "no-shadow": "off",
            "@typescript-eslint/no-shadow": "error",
            "no-throw-literal": "off",
            // "@typescript-eslint/no-throw-literal": "error",
            "no-unused-expressions": "off",
            "@typescript-eslint/no-unused-expressions": "error",
            "no-useless-constructor": "off",
            "@typescript-eslint/no-useless-constructor": "error",
            "space-infix-ops": "off",
            // "@typescript-eslint/space-infix-ops": "error",
            "object-curly-spacing": "off",
            // "@typescript-eslint/object-curly-spacing": ["error", "always"],
            "require-await": "off",
            "@typescript-eslint/require-await": "off",
            "space-before-function-paren": "off",
            // "@typescript-eslint/space-before-function-paren": [
            //     "error",
            //     {
            //         anonymous: "always",
            //         named: "never",
            //         asyncArrow: "always",
            //     },
            // ],
            "no-empty-function": "off",
            "@typescript-eslint/no-empty-function": ["warn"],
            "no-promise-executor-return": "error",
            "array-bracket-spacing": ["error", "never"],
            curly: ["error", "all"],
            eqeqeq: ["error", "always"],
            "guard-for-in": "error",
            "multiline-comment-style": ["error", "separate-lines"],
            "no-confusing-arrow": "error",
            "no-else-return": "error",
            "no-floating-decimal": "error",
            "no-inline-comments": "error",
            "no-lonely-if": "error",
            "no-mixed-operators": "error",
            "no-multi-assign": "error",
            "no-negated-condition": "error",
            "no-nested-ternary": "error",
            "no-param-reassign": "error",
            "prefer-const": "error",
            "prefer-template": "error",
            "spaced-comment": ["error", "always"],
            "arrow-parens": ["error", "always"],
            "arrow-spacing": "error",
            "block-spacing": "error",
            "computed-property-spacing": ["error", "never"],
            "dot-location": ["error", "property"],
            "eol-last": ["error", "always"],
            "func-call-spacing": ["error", "never"],
            "function-call-argument-newline": ["error", "consistent"],
            "implicit-arrow-linebreak": ["off", "beside"],
            "key-spacing": "error",
            "new-parens": "error",
            "no-multi-spaces": "error",
            "no-multiple-empty-lines": "error",
            "no-tabs": "error",
            "no-trailing-spaces": "error",
            "no-whitespace-before-property": "error",
            "rest-spread-spacing": "error",
            "semi-spacing": "error",
            "semi-style": "error",
            "space-before-blocks": "error",
            "space-unary-ops": "error",
            "switch-colon-spacing": "error",
            "template-curly-spacing": "error",
            "prettier/prettier": "warn",
            "sonarjs/no-commented-code": "warn",
            "sonarjs/cognitive-complexity": "warn",
        },
    },
]);
