# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: valkey-{{ .Values.resourceName }}
spec:
  selector:
    app: valkey
    resourceName: {{ .Values.resourceName }}
  ports:
    - port: {{ .Values.valkey.port }}
      targetPort: {{ .Values.valkey.port }}
